# Data Pre-processing (Ananda's Version)

Looking at price and playing with our master .csv file

In [19]:
import pandas as pd
import csv
import numpy as np

In [3]:
df = pd.read_csv('/Users/asantosf/Documents/1.C51/Final Project/1.C51-Final-Project/data/facilities_data_after_dropping_start_dates.csv')
df

,facility_id,facility_name,facility_other_names,sub_site_name,sub_site_other_names,facility_type,primary_commodity,commodities_products,facility_equipment,production_start,production_end,activity_status,activity_status_year,surface_area_sq_km,concession_area_sq_km,country
0,COM00003.00,Absaloka,NaN,NaN,NaN,Mine,Coal,Sub-bituminous coal,NaN,1974.0,NaN,NaN,NaN,NaN,NaN,United States of America
1,COM00005.00,Achinsk Alumina Refinery,NaN,NaN,NaN,Refinery,Processing,"Alumina, Calcined soda",Sinter plant,1970.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
2,COM00008.00,Aguablanca,NaN,NaN,NaN,Mine,Nickel,"Nickel, Copper, Cobalt, Gold, PGM",Underground,2005.0,2016.0,NaN,NaN,NaN,NaN,Spain
3,COM00009.00,Ahafo,NaN,NaN,NaN,Mine,Gold,Gold,"Open pit, Underground",2006.0,NaN,NaN,NaN,NaN,NaN,Ghana
4,COM00015.00,Aktogay,NaN,NaN,NaN,Mine,Copper,"Copper, Silver, Copper cathode, Gold","Open pit, Heap leaching plant",2015.0,NaN,NaN,NaN,NaN,NaN,Kazakhstan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,COM01407.01,Yuzhkuzbassugol,NaN,Alardinskaya,NaN,Mine,Coal,Metallurgical coal,Underground,1957.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
594,COM01407.02,Yuzhkuzbassugol,NaN,Essaulskaya,Yesaulskaya,Mine,Coal,Metallurgical coal,Underground,1984.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
595,COM01407.03,Yuzhkuzbassugol,NaN,Osinnikovskaya,NaN,Mine,Coal,Metallurgical coal,Underground,1933.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
596,COM01407.04,Yuzhkuzbassugol,NaN,Uskovskaya,NaN,Mine,Coal,Metallurgical coal,Underground,2002.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
597,COM01407.05,Yuzhkuzbassugol,NaN,Yerunakovskaya-VIII,Yerunakovskaya-8,Mine,Coal,Metallurgical coal,Underground,2013.0,NaN,NaN,NaN,NaN,NaN,Russian Federation

In [4]:
print(df['primary_commodity'].unique())
print(df['primary_commodity'].value_counts())

<StringArray>
[                 'Coal',            'Processing',                'Nickel',
                  'Gold',                'Copper',             'Aluminium',
                'Silver',                  'Zinc',                  'Iron',
            'Other mine', 'Other (poly)-metallic']
Length: 11, dtype: str
primary_commodity
Coal                     215
Gold                      92
Iron                      75
Copper                    69
Processing                62
Zinc                      18
Other (poly)-metallic     17
Aluminium                 16
Silver                    14
Other mine                11
Nickel                     9
Name: count, dtype: int64

In [5]:
df = df[df['primary_commodity'] != 'Processing'] # removing all of processing 
df = df[df['primary_commodity'] != 'Other mine']

In [6]:
print(df['primary_commodity'].unique())
print(df['primary_commodity'].value_counts())
df

<StringArray>
[                 'Coal',                'Nickel',                  'Gold',
                'Copper',             'Aluminium',                'Silver',
                  'Zinc',                  'Iron', 'Other (poly)-metallic']
Length: 9, dtype: str
primary_commodity
Coal                     215
Gold                      92
Iron                      75
Copper                    69
Zinc                      18
Other (poly)-metallic     17
Aluminium                 16
Silver                    14
Nickel                     9
Name: count, dtype: int64

,facility_id,facility_name,facility_other_names,sub_site_name,sub_site_other_names,facility_type,primary_commodity,commodities_products,facility_equipment,production_start,production_end,activity_status,activity_status_year,surface_area_sq_km,concession_area_sq_km,country
0,COM00003.00,Absaloka,NaN,NaN,NaN,Mine,Coal,Sub-bituminous coal,NaN,1974.0,NaN,NaN,NaN,NaN,NaN,United States of America
2,COM00008.00,Aguablanca,NaN,NaN,NaN,Mine,Nickel,"Nickel, Copper, Cobalt, Gold, PGM",Underground,2005.0,2016.0,NaN,NaN,NaN,NaN,Spain
3,COM00009.00,Ahafo,NaN,NaN,NaN,Mine,Gold,Gold,"Open pit, Underground",2006.0,NaN,NaN,NaN,NaN,NaN,Ghana
4,COM00015.00,Aktogay,NaN,NaN,NaN,Mine,Copper,"Copper, Silver, Copper cathode, Gold","Open pit, Heap leaching plant",2015.0,NaN,NaN,NaN,NaN,NaN,Kazakhstan
5,COM00016.00,Akyem,NaN,NaN,NaN,Mine,Gold,Gold,Open pit,2013.0,NaN,NaN,NaN,NaN,NaN,Ghana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,COM01407.01,Yuzhkuzbassugol,NaN,Alardinskaya,NaN,Mine,Coal,Metallurgical coal,Underground,1957.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
594,COM01407.02,Yuzhkuzbassugol,NaN,Essaulskaya,Yesaulskaya,Mine,Coal,Metallurgical coal,Underground,1984.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
595,COM01407.03,Yuzhkuzbassugol,NaN,Osinnikovskaya,NaN,Mine,Coal,Metallurgical coal,Underground,1933.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
596,COM01407.04,Yuzhkuzbassugol,NaN,Uskovskaya,NaN,Mine,Coal,Metallurgical coal,Underground,2002.0,NaN,NaN,NaN,NaN,NaN,Russian Federation
597,COM01407.05,Yuzhkuzbassugol,NaN,Yerunakovskaya-VIII,Yerunakovskaya-8,Mine,Coal,Metallurgical coal,Underground,2013.0,NaN,NaN,NaN,NaN,NaN,Russian Federation

In [7]:
print(df[df['primary_commodity'] == 'Other (poly)-metallic'])

     facility_id                   facility_name facility_other_names  \
29   COM00082.00                            Azul                  NaN
42   COM00139.00                  Black Mountain                  NaN
87   COM00264.00                          Climax                  NaN
93   COM00277.00                     Collingwood                  NaN
106  COM00321.00                           Daxin                  NaN
164  COM00530.00                       Henderson                  NaN
226  COM00719.00                        Leinster                  NaN
272  COM00844.00                   Morro da Mina                  NaN
276  COM00854.00                    Mount Marion                  NaN
281  COM00862.00                      Mt Cattlin                  NaN
361  COM01100.00                         Rössing                  NaN
411  COM01281.00                        Tiandeng                  NaN
423  COM01310.00                      Two Rivers                  NaN
469  COM00139.02                  Black Mountain                  NaN
548  COM01028.01  PT Central Omega Resources Tbk                  NaN
549  COM01028.02  PT Central Omega Resources Tbk                  NaN
550  COM01028.03  PT Central Omega Resources Tbk                  NaN

                 sub_site_name sub_site_other_names   facility_type  \
29                         NaN                  NaN            Mine
42                         NaN                  NaN            Mine
87                         NaN                  NaN            Mine
93                         NaN                  NaN            Mine
106                        NaN                  NaN  Mine, Refinery
164                        NaN                  NaN            Mine
226                        NaN                  NaN            Mine
272                        NaN                  NaN            Mine
276                        NaN                  NaN            Mine
281                        NaN                  NaN            Mine
361                        NaN                  NaN            Mine
411                        NaN                  NaN  Mine, Refinery
423                        NaN                  NaN            Mine
469                   Gamsberg                  NaN            Mine
548  PT Mulia Pacifc Resources                  MPR            Mine
549      PT Itamatra Nusantara                  IMN            Mine
550          Bumi Konawe Abadi                  BKA            Mine

         primary_commodity                               commodities_products  \
29   Other (poly)-metallic                                          Manganese
42   Other (poly)-metallic                         Zinc, Lead, Silver, Copper
87   Other (poly)-metallic                                         Molybdenum
93   Other (poly)-metallic                                                Tin
106  Other (poly)-metallic  Manganese, Electrolytic manganese metal, Manga...
164  Other (poly)-metallic                                         Molybdenum
226  Other (poly)-metallic                                             Nickel
272  Other (poly)-metallic                                          Manganese
276  Other (poly)-metallic                                            Lithium
281  Other (poly)-metallic                                 Spodumene, Lithium
361  Other (poly)-metallic                                            Uranium
411  Other (poly)-metallic            Manganese, Electrolytic manganese metal
423  Other (poly)-metallic  Platinum, Palladium, Rhodium, Ruthenium, Iridi...
469  Other (poly)-metallic                         Zinc, Copper, Lead, Silver
548  Other (poly)-metallic                                             Nickel
549  Other (poly)-metallic                                             Nickel
550  Other (poly)-metallic                                             Nickel

        facility_equipment  production_start  production_end activity_status  \
29                Open Pit            1985.0             NaN             NaN
42   Open pit, Underground            1980.0             NaN             NaN
87                Open pit            2012.0             NaN             NaN
93             Underground            2006.0          2008.0             NaN
106  Open pit, Underground            1958.0             NaN             NaN
164               Open pit            1976.0             NaN             NaN
226  Open Pit, Underground            1979.0             NaN             NaN
272               Open pit            1902.0             NaN             NaN
276                    NaN            2016.0             NaN             NaN
281               Open pit            2011.0             NaN             NaN
361               Open pit            1976.0             NaN             NaN
411               Open pit            1956.0             NaN             NaN
423            Underground            2007.0             NaN             NaN
469               Open pit            2019.0             NaN             NaN
548                    NaN            2011.0             NaN             NaN
549                    NaN            2013.0             NaN             NaN
550                    NaN            2011.0             NaN             NaN

     activity_status_year  surface_area_sq_km  concession_area_sq_km  \
29                    NaN                 NaN                    NaN
42                    NaN                 NaN                    NaN
87                    NaN            61.10819                    NaN
93                    NaN                 NaN                    NaN
106                   NaN                 NaN                    NaN
164                   NaN            67.58323                    NaN
226                   NaN                 NaN                    NaN
272                   NaN                 NaN                    NaN
276                   NaN                 NaN                    NaN
281                   NaN                 NaN                    NaN
361                   NaN                 NaN                    NaN
411                   NaN                 NaN                    NaN
423                   NaN                 NaN                    NaN
469                   NaN                 NaN                    NaN
548                   NaN                 NaN                 47.800
549                   NaN                 NaN                  9.740
550                   NaN                 NaN                  4.386

                      country
29                     Brazil
42               South Africa
87   United States of America
93                  Australia
106                     China
164  United States of America
226                 Australia
272                    Brazil
276                 Australia
281                 Australia
361                   Namibia
411                     China
423              South Africa
469              South Africa
548                 Indonesia
549                 Indonesia
550                 Indonesia

In [8]:
other_df = df[df['primary_commodity'] == 'Other (poly)-metallic']
print(other_df['commodities_products'].unique())

<StringArray>
[                                                                                                      'Manganese',
                                                                                      'Zinc, Lead, Silver, Copper',
                                                                                                      'Molybdenum',
                                                                                                             'Tin',
 'Manganese, Electrolytic manganese metal, Manganese briquette, Electrolytic manganese dioxide, Manganese sulfate',
                                                                                                          'Nickel',
                                                                                                         'Lithium',
                                                                                              'Spodumene, Lithium',
                                                                                                         'Uranium',
                                                                         'Manganese, Electrolytic manganese metal',
                                  'Platinum, Palladium, Rhodium, Ruthenium, Iridium, Gold, Nickel, Copper, Chrome',
                                                                                      'Zinc, Copper, Lead, Silver']
Length: 12, dtype: str

In [9]:
df_price = pd.read_csv('data/price_data.csv')
df_price

,Year,Coal,Nickel,Gold,Copper,Aluminium,Silver,Zinc,Iron,Other
0,2000,33.20,10856.89,350.72,2279.37,1947.14,6.23,1417.97,36.19,NaN
1,2001,43.21,7762.77,353.86,2060.97,1885.13,5.71,1156.66,39.21,NaN
2,2002,33.91,8947.87,409.58,2060.62,1783.71,6.08,1029.00,38.73,NaN
3,2003,35.37,12094.28,456.56,2234.55,1797.66,6.12,1039.56,40.13,NaN
4,2004,63.29,16256.90,481.26,3370.44,2017.57,7.83,1232.22,44.57,NaN
5,2005,53.49,16811.81,507.23,4194.84,2164.55,8.33,1575.04,74.12,NaN
6,2006,55.48,26970.32,672.01,7474.85,2857.67,12.85,3642.05,77.10,NaN
7,2007,67.27,39012.69,730.09,7459.11,2764.52,14.03,3397.63,128.88,NaN
8,2008,120.44,20529.66,847.72,6764.45,2501.98,14.58,1823.11,151.70,NaN
9,2009,70.77,15192.44,1008.67,5338.73,1725.93,15.18,1715.86,82.91,NaN
10,2010,95.29,21808.85,1224.66,7534.78,2173.12,20.15,2160.74,145.86,NaN
11,2011,107.05,20632.53,1413.19,7950.46,2162.63,31.72,1975.77,151.08,NaN
12,2012,85.86,15919.03,1514.58,7223.39,1835.51,28.25,1769.40,116.57,NaN
13,2013,75.08,13696.40,1286.07,6680.73,1682.61,21.73,1740.55,123.34,NaN
14,2014,65.81,15605.89,1169.12,6340.32,1725.10,17.62,1996.28,89.56,NaN
15,2015,59.08,12120.81,1185.92,5630.38,1700.91,16.06,1973.72,57.07,NaN
16,2016,69.16,10204.38,1328.29,5176.96,1706.03,18.24,2222.67,62.13,NaN
17,2017,89.25,10699.59,1292.59,6341.80,2022.46,17.54,2971.39,73.76,NaN
18,2018,100.46,12874.60,1246.05,6410.56,2069.97,15.43,2869.02,68.48,NaN
19,2019,75.31,13986.64,1399.78,6041.56,1803.87,16.30,2563.74,94.34,NaN
20,2020,64.58,14083.00,1808.23,6306.20,1740.54,20.98,2315.07,111.25,NaN
21,2021,117.87,16878.40,1645.00,8516.50,2260.37,23.00,2744.53,147.82,NaN

In [10]:
# incorporate this into mother - for loop with the name of the "primary_commodity" column - "Other (poly)-metallic" = "Other" in price

In [18]:
mean = df_price.mean()
std = df_price.std()
variation = std*100 / mean
# print(mean, std, variation)

variation = variation[1:]
variation

Coal         35.474096
Nickel       42.727578
Gold         44.618964
Copper       36.279669
Aluminium    16.735645
Silver       45.612329
Zinc         35.495394
Iron         44.939300
Other              NaN
dtype: float64

In [ ]:
# encoding average price variation into average_data (created after much of this code)
average_data = pd.read_csv('data/average_data.csv')

ohe_cols = [col for col in average_data.columns if col.startswith("primary_commodity_")]

def get_variation(row):
    for col in ohe_cols:
        if row[col] == 1:
            commodity = col.replace("primary_commodity_", "")
            return variation.get(commodity, np.nan)
    return np.nan

In [21]:
average_data["commodity_var"] = average_data.apply(get_variation, axis=1)

In [22]:
average_data

,facility_id,total_reserves_minerals,total_reserves_commodities,avg_reserves_grade_ppm,avg_commodity_recovery_rate,avg_commodities_grade_ppm,total_coal,total_commodities,total_minerals,primary_commodity,...,primary_commodity_Copper,primary_commodity_Gold,primary_commodity_Iron,primary_commodity_Nickel,primary_commodity_Other (poly)-metallic,primary_commodity_Other mine,primary_commodity_Silver,primary_commodity_Zinc,avg_price_usd,commodity_var
0,COM00003.00,1.094375e+09,0.000000,NaN,NaN,NaN,85716792.0,0.000,0.0,Coal,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.988824,35.474096
1,COM00009.00,2.961694e+09,273.289402,1.594967,0.920600,1.873773,0.0,184.360,129637066.0,Gold,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,19845.493636,44.618964
2,COM00015.00,1.399000e+09,0.000000,NaN,NaN,149375.257990,0.0,196800.000,48136000.0,Copper,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1165.624286,36.279669
3,COM00016.00,6.189506e+08,73.141769,1.216045,0.913600,1.700082,0.0,80.851,61959946.0,Gold,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5920.252000,44.618964
4,COM00017.00,1.184937e+09,0.000000,NaN,NaN,NaN,0.0,0.000,19521911.0,Aluminium,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1272.545714,16.735645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,COM01415.00,0.000000e+00,0.000000,NaN,NaN,NaN,35811100.0,0.000,0.0,Coal,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,35.474096
370,COM01418.00,0.000000e+00,9.896000,7.880000,NaN,NaN,0.0,20.241,0.0,Gold,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,44.618964
371,COM01419.00,2.500000e+07,0.000000,NaN,NaN,NaN,31357000.0,0.000,0.0,Coal,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5428.443500,35.474096
372,COM01430.00,0.000000e+00,0.357000,0.320000,NaN,NaN,0.0,239.953,0.0,Gold,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,64.580000,44.618964
373,COM01432.00,9.430307e+07,822.136171,82.000000,0.872375,11713.680192,0.0,21959.305,6365855.0,Zinc,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,14.999000,35.495394

In [24]:
# let's save, yay!
average_data.to_csv("data/average_data.csv", index=False)